spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/academiaFutbol
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ajustes de optimización del Pool de Conexiones
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.connection-timeout=300000
spring.datasource.hikari.validation-timeout=5000

# Asegura que verifique si la conexión sirve antes de dársela a Hibernate
spring.datasource.hikari.connection-test-query=SELECT 1